### ISSUE TITLE
Time stamps fix

### ISSUE THREAD

**Issue by lejlac** [occrp/id-backend#111]
Time stamps now say "xy days ago" or "xy hours ago" and when you hover over that, it shows exact date and time.
I can propose two solutions:
- display full time stamp like the one that's displayed when we hover over it
- do what phones do in chats. Say: today, yesterday and everything before that display as specific date

Time is always set to Sarajevo -1 hour. Can we put it to Sarajevo time, please.

**Comment by lejlac** [comment]
I just wanted to add that I was talking about both Comments and Attached files.
At the moment. It's not possible to determine which file was uploaded at which time.
Instead of file size, I'd like there to be time of upload.

**Comment by stas** [comment]
@sungraze it looks like this was not done, do you think we can have it in this milestone or should I move it into V3.1?
