### ISSUE TITLE
Show icons/gravatars for responders

### ISSUE THREAD

**Issue by pudo** [occrp/id-backend#113]
So users can see who they are being served by

**Comment by lejlac** [comment]
Will send pictures tomorrow.

**Comment by stas** [comment]
@lejlac we will either provide a way to update the pics, or use gravatar where possible. No need to send pics unless it's for the website.

**Comment by sungraze** [comment]
Avatar support is in place with the user's initials as a fallback (currently everyone has these).

To add pics I'll need them exposed through the API, assuming we add an uploader somewhere on a user's profile setting. Gravatar is also doable.
