### ISSUE TITLE
Add any user to a ticket

### ISSUE THREAD

**Issue by lejlac** [occrp/id-backend#115]
This has proven to be a major priority for us in the last two weeks. Please squeeze it in somewhere as soon as possible.

**Comment by lejlac** [comment]
It should only be possible to add users by entering their email address, not the first and last name credentials.

**Comment by stas** [comment]
@sungraze we need to update the email attribute from `user-email` to just `email` on subscribers endpoint. The relevant change is here:
https://github.com/occrp/id-backend/commit/c8ad385861f563c690d7559627443721b85bfd0b#diff-0919974d21e27919ea82a9fc4bb930c9L42
