### ISSUE TITLE
Admin flag does not get removed

### ISSUE THREAD

**Issue by pudo** [occrp/id-backend#131]
I've tried for a while to remove the `is_superuser` flag from certain users but it seems that it gets re-applied every time they log in. Can we check the logic for how this is decided and make sure it applies only to members of the research team and the associated group in Keycloak?

**Comment by rysiekpl** [comment]
Isn't it governed by the "superuser" group in Keycloak?

**Comment by stas** [comment]
@rysiekpl is right, we sync with data from Keycloak:
https://github.com/occrp/id-backend/blob/master/api_v3/misc/oauth2.py#L25-L31

Should we not?

**Comment by rysiekpl** [comment]
I see. Ok, I'll fix this on the Keycloak side. Was meaning to clean-up the groups a bit anyway. Thanks.

Not sure if it makes sense to keep this ticket open, then.
