### ISSUE TITLE
Databases

### ISSUE THREAD

**Issue by stas** [occrp/id-backend#45]
Currently, the External Databases from https://investigativedashboard.org/databases/ require server-side support. 

After reviewing the data, we decided we can use Jekyll Data Files support to help with that:
https://jekyllrb.com/docs/datafiles/

Basically, we need to export the data we have into a normalized YAML/CSV file and feed it to Jekyll.

There's a repository with a snapshot of our website, but there's no Database work done yet:
https://github.com/occrp/investigativedashboard.org

If you need help with the CSS/layout, ping @stas or @sungraze

**Comment by stas** [comment]
@pudo if you have time to look into this, this commit might be relevant to the issue:
https://github.com/occrp/investigativedashboard.org/commit/5718e8cffb0d98bf0cc70a211d43486b5da39c0b

**Comment by stas** [comment]
@pudo or @ancagrosan, if you have time, feel free to assign the ticket to yourself and work on it.

Any help is much appreciated!

**Comment by ancagrosan** [comment]
I'll look into this, I can't assign myself.

**Comment by stas** [comment]
Weird, can't assign you too. @pudo could you check the settings, please?

**Comment by stas** [comment]
@ancagrosan do you have an update on this please 🙏 😄  ?

**Comment by ancagrosan** [comment]
not since we've last spoken, I'll try to do some of the things we talked about over the next days

**Comment by stas** [comment]
This landed in https://github.com/occrp/investigativedashboard.org/commit/74cfd5b2c5e2cba6b006438b64c3d741eab648ba

A preview is available at https://occrp.github.io/investigativedashboard.org/databases/

**Comment by stas** [comment]
@ancagrosan thank you for helping with this!
