### ISSUE TITLE
Requester bio

### ISSUE THREAD

**Issue by stas** [occrp/id-backend#47]
Before a user can fill in a ticket, he should provide some bio/introduction info.

**Comment by sungraze** [comment]
We've settled on making a patch to `/profiles` when a user submits it's first ticket and include a new `bio` attr. We have a `ticket-count` attr already to determine this and I'll also include redirecting to the create form when it is 0 to avoid seeing an empty list first time you login.

**Comment by pudo** [comment]
Feedback from @lejlac -- it would be good to instead show a list of all tickets associated with the user selected. An "organisation" field is also wanted, but we need to sync with @rysiekpl on whether this should live in ID or in SSO.

**Comment by pudo** [comment]
Footnote: In a luxurious future, show a summarized overview of which responders have handled which requester, to basically see who is "responsible" for whose tickets by tradition.

**Comment by lejlac** [comment]
I agreed verbally with both Pudo's comments from Oct 16. But I don't know if we did run this by @rysiekpl
