### ISSUE TITLE
Remove unneeded assets from the old app 

### ISSUE THREAD

**Issue by sungraze** [occrp/id-backend#61]
1. Remove [`app.js`](https://staging.occrp.org/static/app.js?fbf7658a) which is 100KB of gzipped stuff we don't need. The only usecase is making the dropdown from the main nav work.

2. Remove all the css too. RIP Bootstrap.

3. Extract only the small bits necessary for the main nav to look & work the same.

**Comment by stas** [comment]
Closed partially by #120 and https://github.com/occrp/investigativedashboard.org/commit/02e219d9b01f86185d9ca2e2eda1e48451ae258c
