### ISSUE TITLE
Updated = Date Filed

### ISSUE THREAD

**Issue by lejlac** [occrp/id-backend#69]
The Updated under the request title actually indicates when the request was filed

**Comment by sungraze** [comment]
@stas looks like `created-at` and `updated-at` stay the same after leaving a comment (for example). So basically `updated-at` is lagging behind.

**Comment by stas** [comment]
Hmm,
@lejlac please confirm you want us to update the ticket update timestamp if there's a comment or other changes related to the ticket.

**Comment by lejlac** [comment]
yes, the timestamp should be updated.
