### ISSUE TITLE
Can't see all requests by one user

### ISSUE THREAD

**Issue by lejlac** [occrp/id-backend#71]
I can't type in a name of the user and get requests history for a user.
Even if I could, that's rather impractical. I'd much rather click on a name and see a list of all their requests (open and closed)

**Comment by sungraze** [comment]
This is 👍 as we discussed on Slack and will also cover #74

**Comment by stas** [comment]
The tickets endpoint already provides a filter for this. For ex.:
```
/api/v3/tickets?filter[responders__user]=6059
```
