### ISSUE TITLE
Make requeser's name clickable

### ISSUE THREAD

**Issue by lejlac** [occrp/id-backend#74]
Can we make requester's name clickable. It should redirect to their little profile on the admin side, which only I should be able to see, not other researchers. Sometimes I can figure out who they work for from their email address.
I don't know if it could be combined with seeing the list of all requests a requester has posted.

**Comment by sungraze** [comment]
We can link to the lists of requests since it's basically a filter on the index.

Additionally, when you are an admin, we could add an external link somewhere on that page (the filtered list) but this is something @stas should have a look at to see if there's something we can link to.

**Comment by stas** [comment]
I'll ping Lejla to learn about this Admin part a bit :|

**Comment by stas** [comment]
@sungraze sorry for the delay on this.

Is it possible to provide an option/link to the following URL if a superuser is logged in:
`/admin/accounts/profile/{ID}`

This is relevant only in the context of the Ticket, specifically the requestor profile.
This will eventually evolve into something like #47
