### ISSUE TITLE
Filter by requester's name doesn't work

### ISSUE THREAD

**Issue by lejlac** [occrp/id-backend#76]

**Comment by stas** [comment]
The API already provides a filter for requesters:

For ex.:
```
/api/v3/tickets?filter[requester]=4293
```

**Comment by pudo** [comment]
The issue here is apparently that the suggestions in the autocomplete do not contain good matches. This might be due to non-ascii names or an internal bug. Can we improve this by making the search work against ASCII names, or something like that?
