### ISSUE TITLE
Index page shows total ticket count, not just those visible to a user

### ISSUE THREAD

**Issue by pudo** [occrp/id-backend#84]
When I log in to a normal user account, ID tells me that there are 1900 tickets but I cannot see any of them. Shouldn't the total shown be the number of tickets visible to a user, instead of the overall count in the system?

**Comment by stas** [comment]
This looks fixed in 7116bc53bcc5643b311fcd942bb783cd10ea22cd.
Please reopen if it persists with some details to reproduce.

Ty
