### ISSUE TITLE
Add search requests function?

### ISSUE THREAD

**Issue by lejlac** [occrp/id-backend#89]
Maybe I should have asked for it before but I just realized there is no good way for me to find requests. I can't filter by requester and if I filter by researcher, I still get too many in the results.

**Comment by stas** [comment]
@lejlac makes sense. I can include this in the next release.

**Comment by stas** [comment]
@sungraze let me know if you have time for it for v2.6

**Comment by pudo** [comment]
Could still fit into Milestone 2.7? Rated less important than #72.

**Comment by sungraze** [comment]
The UI is ready for this.

@stas I've used `filter[name]=term` for now but let me know if we should change to `filter[search]` or smth.

**Comment by stas** [comment]
`filter[search]` is the right API call :)
