### ISSUE TITLE
Attach files while filing requests

### ISSUE THREAD

**Issue by lejlac** [occrp/id-backend#90]
In order to attach files users have to fill out the request, click submit and after that Attach files function appears. That's not intuitive and it's not indicated anywhere in the process. Is it possible to attach files during request filing process?

**Comment by stas** [comment]
@sungraze maybe we can have a UX trick to have this, something like a two-step wizard? First step fill-in the ticket, second add any attachments.

What do you think?

**Comment by sungraze** [comment]
We could change the wording from "Submit"  to "Continue" or "Next step" and highlight the upload area (which I'd like to place more upfront anyway #spoilers) when taken to the ticket page.

**Comment by pudo** [comment]
Talking with @lejlac, it appears that a small note ("You can attach documents after submitting the request") would be sufficient to meet this need.
